[project]
name = "weather-tracker-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "supabase>=2.18.1",
    "uvicorn>=0.35.0",
]
